### ISSUE TITLE
Bot incorrectly enters Vermittlungscodes

### ISSUE THREAD

**Issue by fabianhick** [TobseF/impf-bot#48] opened 2021-05-16 16:42 UTC
Thanks for developing this bot!

However, it seems that it unfortunately mistypes the Vermittlungscode on the booking page (i.e. only fills in the first two blanks, but misses the first letter) and then throws an error:

````
impf-bot    | 16.05 16:35:20 ERROR ReportJob - Failed to check location: 72072 T?bingen
impf-bot    | element click intercepted: Element <button _ngcontent-nfa-c113="" type="submit" class="btn kv-btn btn-magenta text-uppercase d-inline-block" disabled="">...</button> is not clickable at point (467, 499). Other element would receive the click: <div _ngcontent-nfa-c113="" class="form-group text-center">...</div>
impf-bot    |   (Session info: chrome=90.0.4430.93)
impf-bot    | Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
impf-bot    | System info: host: '6adf4305179a', ip: '172.28.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-141-generic', java.version: '11.0.11'
impf-bot    | Driver info: org.openqa.selenium.chrome.ChromeDriver
impf-bot    | Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 90.0.4430.93, chrome: {chromedriverVersion: 90.0.4430.24 (4c6d850f087da..., userDataDir: /tmp/.com.google.Chrome.TyvRGF}, goog:chromeOptions: {debuggerAddress: localhost:40049}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
impf-bot    | Session ID: 9f166dc743c26769d1d90159048048e9
impf-bot    | org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element <button _ngcontent-nfa-c113="" type="submit" class="btn kv-btn btn-magenta text-uppercase d-inline-block" disabled="">...</button> is not clickable at point (467, 499). Other element would receive the click: <div _ngcontent-nfa-c113="" class="form-group text-center">...</div>
impf-bot    |   (Session info: chrome=90.0.4430.93)
impf-bot    | Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
impf-bot    | System info: host: '6adf4305179a', ip: '172.28.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-141-generic', java.version: '11.0.11'
impf-bot    | Driver info: org.openqa.selenium.chrome.ChromeDriver
impf-bot    | Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 90.0.4430.93, chrome: {chromedriverVersion: 90.0.4430.24 (4c6d850f087da..., userDataDir: /tmp/.com.google.Chrome.TyvRGF}, goog:chromeOptions: {debuggerAddress: localhost:40049}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
impf-bot    | Session ID: 9f166dc743c26769d1d90159048048e9
impf-bot    |   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
impf-bot    |   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
impf-bot    |   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
impf-bot    |   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
impf-bot    |   at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
impf-bot    |   at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
impf-bot    |   at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
impf-bot    |   at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
impf-bot    |   at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
impf-bot    |   at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
impf-bot    |   at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
impf-bot    |   at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
impf-bot    |   at de.tfr.impf.page.LocationPage.submitInput(LocationPage.kt:33)
impf-bot    |   at de.tfr.impf.page.LocationPage.searchForFreeDate(LocationPage.kt:66)
impf-bot    |   at de.tfr.impf.ReportJob.searchFreeDateByCode(ReportJob.kt:100)
impf-bot    |   at de.tfr.impf.ReportJob.checkLocation(ReportJob.kt:68)
impf-bot    |   at de.tfr.impf.ReportJob.checkLocations(ReportJob.kt:44)
impf-bot    |   at de.tfr.impf.ReportJob.reportFreeSlots(ReportJob.kt:37)
impf-bot    |   at de.tfr.impf.StartKt.main(Start.kt:4)
impf-bot    |   at de.tfr.impf.StartKt.main(Start.kt)
```

**Comment by madrhr** [comment] 2021-05-16 16:50
Based on your specific exception, I think your problem is more because of the 'ü' in Tübingen. This is a previous problem of this project. Basicly you have 2 options.
1. remove die city name and use just the zip code (works perfectly fine)
2. search the closed issues, I think this was mentioned (and maybe fixed) before

**Comment by fabianhick** [comment] 2021-05-16 16:55
I just tried it with just the zip code, but unfortunately the error persists.

**Comment by madrhr** [comment] 2021-05-16 16:59
Is it only for the city of Tübingen or other cities aswell?

**Comment by fabianhick** [comment] 2021-05-16 17:08
It seems to work in another city, maybe it is also just because the Vermittlungscode for Tübingen starts with a number in comparison to my other.

**Comment by dirkbloessl** [comment] 2021-05-16 17:46
I have a similar issue. City is Hamburg. The second segment is X6WL and the bot just does not enter the 6. If I change it to XXWL it works.
I'm currently digging in the code, why this happens...

**Comment by spozer** [comment] 2021-05-16 17:58
I also noticed that a '5' acts as a backspace some how. But it only occurs for me when running in the Docker container. I think it has something to do with the VNC server, because through the VNC web client the same thing happens for keyboard inputs.

**Comment by Pfuenzle** [comment] 2021-05-16 18:16
Oh I didn't run into this yet, as non of my Vermittlungscodes I'm checking have an numbers in them. Ill test some other keyboard layouts for the VNC server and then create a pull request

**Comment by atpanos** [comment] 2021-05-17 10:22
try to save the config.properties as UTF8

**Comment by Bergdoc** [comment] 2021-05-18 13:17
I face the same issue with the numbers 5 and 6 while running inside a docker container (there is also a different output when I type these numbers over the VNC web client).
Saving the config.properties as UTF8 did not help for me. Has anyone found a workaround (beside generating new "Vermittlungscodes" until they don't have a 5 or 6 inside)?

**Comment by Pfuenzle** [comment] 2021-05-18 13:26
It seems 5 and 6 get mapped to wrong keys or no key at all, (thanks random bug report from 2001). I'm trying to find the best way to remap them, will make a commit in the next few hours

**Comment by Pfuenzle** [comment] 2021-05-18 14:33
Keys 5 & 6 are fixed with the newest Containerupdate, I hope this fixes this issue

**Comment by Bergdoc** [comment] 2021-05-18 15:37
I just had a quick look and for me it seems like the issue is still there. Typing 5 and 6 is not possible. I'll have a closer look later, if I missed something.

**Comment by Pfuenzle** [comment] 2021-05-18 16:18
I forgot to apply the patch to the ARM image, just made a commit.

**Comment by Bergdoc** [comment] 2021-05-18 18:47
I still face some issues, I think the key-mapping is done correctly, since I can use now the numbers 5 and 6 inside the vnc client. But somehow it seems that chromium is not using the mapping correctly? Since when I try to use 5 and 6 it works with my numpad (somehow 8 will result in fullscreen) but the normal 5 and 6 is not working inside chromium browser.
https://bugs.chromium.org/p/chromium/issues/detail?id=394552
Do you have any suggestions? Or is it fixed inside your docker container? Thanks for the help btw :)

**Comment by Pfuenzle** [comment] 2021-05-18 19:27
I should have fixed it with the newest Dockerfile, but I only tested it in Firefox as I didnt think it would make a difference, but youre right, in Chromium its not working. I will look into that

**Comment by Pfuenzle** [comment] 2021-05-18 19:44
Alright, made a Pull request, now Chrome also accepts the keymappings.
No idea why they were ignored in the first place, but whatever

**Closed as completed** 2021-05-18 20:37 UTC
